### ISSUE TITLE
Unable to manipulate playlists.

### ISSUE THREAD

**Issue by Fukutaro-dev** [Loloppe/BeatSaber_BeatmapScanner#1]
Hi!Loloppe.
BeatmapScanner 1.1.1
Operations such as adding and deleting playlists are no longer possible.
![image](https://user-images.githubusercontent.com/80106416/212846772-36d145e5-dd0a-45f8-b9cd-29667bae5b44.png)

Best regards
HPC.

**Comment by Loloppe** [comment]
Thank you for letting me know. It is fixed in the new release 1.1.2.
